version: '2'
services:
  backend-service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
     - the-postgres
    links:
     - the-postgres
  the-postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./data/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres