version: '2'
services:
  the-postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./data/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres